/**
 * Janki Framings - Comprehensive Framing Product Catalog
 * Serving Indian Retail Customers, Pooja Mandirs, Corporate Offices & Bulk Wholesale Retailers
 * Primary Focus: Hindu Gods' Frames, Marriage/Wedding, Corporate, Bulk Cartons & Framing Materials
 */

const CATEGORIES_DATA = [
  {
    id: 'all',
    name: 'All Framing Collections',
    icon: '🪟',
    count: 20,
    photoUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=700&auto=format&fit=crop&q=80',
    description: 'Complete range of Hindu God frames, grand wedding portraits, corporate degrees, and bulk materials.'
  },
  {
    id: 'hindu-gods',
    name: "Hindu Gods' Pooja Frames",
    icon: '🕉️',
    count: 6,
    isPrimary: true,
    photoUrl: 'https://images.unsplash.com/photo-1582561424760-0321d75e81fa?w=700&auto=format&fit=crop&q=80',
    description: 'Shree Ram, Radha Krishna, Balaji, Shiva & Ganesha in 24K gold foil, 3D embossed acrylic & teak wood.'
  },
  {
    id: 'wedding-marriage',
    name: 'Marriage & Couple Photos',
    icon: '💍',
    count: 3,
    photoUrl: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=700&auto=format&fit=crop&q=80',
    description: 'Royal wedding portraits, pre-wedding couple canvas floaters, vintage gold leaf and memory collages.'
  },
  {
    id: 'corporate-framing',
    name: 'Corporate & Certificates',
    icon: '🏢',
    count: 3,
    photoUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=700&auto=format&fit=crop&q=80',
    description: 'Degree certificates, executive boardroom art, employee appreciation awards and bulk office decor.'
  },
  {
    id: 'bulk-retail-cartons',
    name: 'Retailer Bulk Cartons',
    icon: '📦',
    count: 3,
    photoUrl: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=700&auto=format&fit=crop&q=80',
    description: 'Master carton packs (12 to 50 pcs) for gift shops, temple souvenir stores and stationery retailers.'
  },
  {
    id: 'family-personal',
    name: 'Family & Baby Collages',
    icon: '👨‍👩‍👧',
    count: 2,
    photoUrl: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?w=700&auto=format&fit=crop&q=80',
    description: 'Multi-aperture family trees, newborn milestone collages, and contemporary home gallery walls.'
  },
  {
    id: 'mouldings',
    name: 'Raw & Gold Moulding Sticks',
    icon: '🪵',
    count: 2,
    photoUrl: 'https://images.unsplash.com/photo-1516455590571-18256e5bb9ff?w=700&auto=format&fit=crop&q=80',
    description: 'PS synthetic gold moulding bars and seasoned teak wood lengths (bundles of 10 × 9.5 ft) for workshops.'
  },
  {
    id: 'framing-materials',
    name: 'Glass, Mounts & Hardware',
    icon: '🔩',
    count: 1,
    photoUrl: 'https://images.unsplash.com/photo-1581244277943-fe4a9c777189?w=700&auto=format&fit=crop&q=80',
    description: '2mm clear sheet glass, acid-free velvet mountboards, heavy-duty D-rings, wire and flexipoints.'
  }
];

// Product listings with dual Retail and Wholesale parameters in INR (₹)
const PRODUCTS_DATA = [
  // --- Category: Hindu Gods (Primary) ---
  {
    id: 'god-001',
    name: 'Shree Ram Darbar Tanjore Style 24K Gold Foil Ornate Frame',
    sku: 'JNK-RAM-1824',
    category: 'hindu-gods',
    audience: ['retail', 'wholesale'],
    priceRetail: 2850,
    priceWholesale: 1550,
    wholesalePackInfo: 'Wholesale Tier: 5+ frames (₹1,550 ea - Save 45%)',
    moq: 5,
    rating: 5.0,
    reviewsCount: 342,
    salesCount: 4890,
    isBestseller: true,
    bestsellerType: 'god-frames',
    material: 'Antique Carved Synthetic & Gold Leaf',
    finish: 'Temple Antique Gold',
    dimensions: '18" × 24" (Outer 22" × 28")',
    inStock: true,
    stockCount: 140,
    photoUrl: 'https://images.unsplash.com/photo-1582561424760-0321d75e81fa?w=600&auto=format&fit=crop&q=80',
    description: 'Sacred Tanjore style Shree Ram, Sita Mata, Lakshman Ji and Hanuman Ji. Hand-embossed 24K gold foil relief with Jaipur stone work, housed in a traditional carved antique gold mandir frame with 2mm float glass.',
    specs: {
      deity: 'Shree Ram Darbar',
      frameProfile: '55 mm Heavy Antique Floral Moulding',
      embossWork: '24K Micron Gold Foil with Sparkling Stonework',
      glazing: '2.0mm Clean Washed Sheet Glass',
      backing: 'Moisture-resistant MDF with brass hanging hooks'
    }
  },
  {
    id: 'god-002',
    name: 'Radha Krishna Divine Romance 3D Embossed Acrylic Backlit Frame',
    sku: 'JNK-RDK-1620',
    category: 'hindu-gods',
    audience: ['retail', 'wholesale'],
    priceRetail: 1950,
    priceWholesale: 1050,
    wholesalePackInfo: 'Min. 6 units for Wholesale (₹1,050 ea)',
    moq: 6,
    rating: 4.9,
    reviewsCount: 215,
    salesCount: 3620,
    isBestseller: true,
    bestsellerType: 'god-frames',
    material: 'Teak Finish Wood & Acrylic',
    finish: 'Warm Teak Wood',
    dimensions: '16" × 20" (Pooja Room & Living Wall)',
    inStock: true,
    stockCount: 220,
    photoUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=600&auto=format&fit=crop&q=80',
    description: 'Vibrant divine depiction of Shree Radha Krishna in Vrindavan. Featuring embossed acrylic texture that catches pooja diya lighting beautifully. Fitted in seasoned teakwood-tone synthetic frame.',
    specs: {
      deity: 'Radha Krishna',
      frameProfile: '40 mm Deep Bevel Teak Moulding',
      glazing: 'Anti-Glare Clear Polycarbonate Sheet',
      illumination: 'Pre-wired for optional warm-white LED backlighting',
      usage: 'Ideal for Pooja Mandir, Living Room & Griha Pravesh Gift'
    }
  },
  {
    id: 'god-003',
    name: 'Tirupati Balaji (Venkateswara Swamy) Grand Golden Mandir Frame',
    sku: 'JNK-BLJ-2030',
    category: 'hindu-gods',
    audience: ['retail', 'wholesale'],
    priceRetail: 3400,
    priceWholesale: 1850,
    wholesalePackInfo: 'Wholesale: 4+ units (₹1,850 ea)',
    moq: 4,
    rating: 5.0,
    reviewsCount: 188,
    salesCount: 2750,
    isBestseller: true,
    bestsellerType: 'god-frames',
    material: 'Solid Polymer & Brass Inlay',
    finish: 'Royal Gold & Velvet',
    dimensions: '20" × 30" (Grand Mandir Size)',
    inStock: true,
    stockCount: 85,
    photoUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80',
    description: 'Majestic Lord Venkateswara Swamy in full Alankaram with Shankha, Chakra and Namam. Backed on royal maroon velvet matting with a heavy 3-step temple stepped gold moulding.',
    specs: {
      deity: 'Lord Venkateswara Balaji',
      frameProfile: '65 mm Triple-Step Traditional Temple Frame',
      matboard: 'Deep Crimson Royal Velvet Mount',
      glazing: '2.5 mm High Clarity Glass',
      weight: 'Approx 3.8 kg with reinforced iron D-rings'
    }
  },
  {
    id: 'god-004',
    name: 'Mahadev Shiva Parvati & Ganesha Kailash Parivar Frame',
    sku: 'JNK-SHV-1824',
    category: 'hindu-gods',
    audience: ['retail', 'wholesale'],
    priceRetail: 2200,
    priceWholesale: 1200,
    wholesalePackInfo: 'Wholesale Tier: 5+ frames (₹1,200 ea)',
    moq: 5,
    rating: 4.8,
    reviewsCount: 142,
    salesCount: 2100,
    isBestseller: false,
    material: 'Composite Timber',
    finish: 'Matte Charcoal & Gold',
    dimensions: '18" × 24" Portrait',
    inStock: true,
    stockCount: 110,
    photoUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&auto=format&fit=crop&q=80',
    description: 'Complete Shiv Parivar on holy Mount Kailash with Nandi and Kartikeya. Muted divine artwork complemented by a dual charcoal-black outer frame with inner gold fillet liner.',
    specs: {
      deity: 'Shiv Parivar (Shiva, Parvati, Ganesha, Kartikeya)',
      frameProfile: '45 mm Dual-Tone Modern Mandir Frame',
      finishTone: 'Matte Charcoal with 8mm Gold Beaded Fillet',
      backing: 'Termite-treated hardboard'
    }
  },
  {
    id: 'god-005',
    name: 'Maa Lakshmi & Lord Ganesha Diwali Auspicious Pooja Frame',
    sku: 'JNK-LKG-1216',
    category: 'hindu-gods',
    audience: ['retail', 'wholesale'],
    priceRetail: 1450,
    priceWholesale: 780,
    wholesalePackInfo: 'Min. 10 units (₹780 ea - Top Diwali Resale Item)',
    moq: 10,
    rating: 4.9,
    reviewsCount: 290,
    salesCount: 6400,
    isBestseller: true,
    bestsellerType: 'god-frames',
    material: 'Gold Finished Polymer',
    finish: 'Temple Antique Gold',
    dimensions: '12" × 16" (Standard Home & Shop Mandir)',
    inStock: true,
    stockCount: 450,
    photoUrl: 'https://images.unsplash.com/photo-1577083552431-6e5fd01aa342?w=600&auto=format&fit=crop&q=80',
    description: 'High-volume favorite for Diwali pooja, new shop openings (Vastu/Muhurat), and corporate festive gifting. Features Goddess Lakshmi showering gold coins alongside Vighnaharta Ganesha.',
    specs: {
      deity: 'Lakshmi & Ganesha',
      frameProfile: '35 mm Golden Peacock Bead Moulding',
      glazing: '2.0mm High Transparency Glass',
      packaging: 'Individually boxed in auspicious festive red gift box'
    }
  },
  {
    id: 'god-006',
    name: 'Panchamukhi Hanuman Ji (Sankat Mochan) Heavy Protection Frame',
    sku: 'JNK-HNM-1420',
    category: 'hindu-gods',
    audience: ['retail', 'wholesale'],
    priceRetail: 1850,
    priceWholesale: 990,
    wholesalePackInfo: 'Wholesale: 6+ units (₹990 ea)',
    moq: 6,
    rating: 5.0,
    reviewsCount: 165,
    salesCount: 2340,
    isBestseller: false,
    material: 'Dark Sheesham Finish Wood',
    finish: 'Warm Teak Wood',
    dimensions: '14" × 20" Wall Mount',
    inStock: true,
    stockCount: 95,
    photoUrl: 'https://images.unsplash.com/photo-1582561424760-0321d75e81fa?w=600&auto=format&fit=crop&q=80',
    description: 'Fierce and protective Panchamukhi Hanuman representation. High-definition gold-ink lithograph print in dark Sheesham wood-textured heavy moulding.',
    specs: {
      deity: 'Panchamukhi Hanuman',
      frameProfile: '42 mm Heavy Ribbed Profile',
      protection: 'UV-resistant protective coating on glass'
    }
  },

  // --- Category: Marriage & Couple Photos ---
  {
    id: 'mrg-001',
    name: 'Royal Heritage Indian Wedding Couple Portrait Frame (Gold & Ivory)',
    sku: 'JNK-WED-2436',
    category: 'wedding-marriage',
    audience: ['retail', 'wholesale'],
    priceRetail: 4200,
    priceWholesale: 2350,
    wholesalePackInfo: 'Wholesale / Studio Partners: 3+ units (₹2,350 ea)',
    moq: 3,
    rating: 5.0,
    reviewsCount: 148,
    salesCount: 1820,
    isBestseller: true,
    bestsellerType: 'marriage',
    material: 'Hand-Carved Wood Finish',
    finish: 'Temple Antique Gold',
    dimensions: '24" × 36" (Grand Master Bedroom Size)',
    inStock: true,
    stockCount: 60,
    photoUrl: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=600&auto=format&fit=crop&q=80',
    description: 'Designed exclusively for Indian wedding photography couples and professional bridal studios. Features double ivory French matting with gold bead liner inside a rich Victorian ornate golden border.',
    specs: {
      profileWidth: '70 mm (2.75 in) Luxury Gold Leaf Moulding',
      matOpening: '20" × 30" Cutout (4-ply Beveled Ivory Mat)',
      glazing: 'Optical grade anti-reflective glass',
      backing: 'Termite & moisture resistant wood back with heavy hanging brackets'
    }
  },
  {
    id: 'mrg-002',
    name: 'Pre-Wedding Canvas Floater Frame - Modern Walnut Shadowbox',
    sku: 'JNK-FLT-2030',
    category: 'wedding-marriage',
    audience: ['retail', 'wholesale'],
    priceRetail: 2700,
    priceWholesale: 1450,
    wholesalePackInfo: 'Wholesale: 5+ frames (₹1,450 ea)',
    moq: 5,
    rating: 4.9,
    reviewsCount: 92,
    salesCount: 1450,
    isBestseller: false,
    material: 'Solid Wood',
    finish: 'Warm Teak Wood',
    dimensions: '20" × 30" (1.5" Canvas Depth)',
    inStock: true,
    stockCount: 80,
    photoUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=600&auto=format&fit=crop&q=80',
    description: 'Sleek canvas floater that leaves a stylish 10mm shadow gap around your stretched canvas couple portrait. Trendy modern aesthetic loved by young couples.',
    specs: {
      profileDepth: '45 mm (1.75 in) deep rebate',
      compatibility: 'Fits stretched canvas wraps up to 1.5" thickness',
      origin: 'Solid pine core with warm walnut finish'
    }
  },
  {
    id: 'mrg-003',
    name: 'Shaadi Memory Collage Frame (9 Multi-Photo Aperture)',
    sku: 'JNK-COL-1824',
    category: 'wedding-marriage',
    audience: ['retail', 'wholesale'],
    priceRetail: 1800,
    priceWholesale: 980,
    wholesalePackInfo: 'Wholesale: 6+ units (₹980 ea)',
    moq: 6,
    rating: 4.8,
    reviewsCount: 110,
    salesCount: 2200,
    isBestseller: true,
    bestsellerType: 'marriage',
    material: 'Composite Timber',
    finish: 'Crisp White',
    dimensions: '18" × 24" Mat with 9 Photo Openings',
    inStock: true,
    stockCount: 130,
    photoUrl: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&auto=format&fit=crop&q=80',
    description: 'Celebrate Haldi, Mehendi, Sangeet, Varmala and Reception in one frame. Precision computer-cut archival mount holds one 8×10 center photo and eight 4×6 candid shots.',
    specs: {
      apertures: '1 Center (8×10) + 8 Surrounding (4×6)',
      mountBoard: '100% Acid-free Pure White 4-Ply Board',
      glazing: '2.0mm Clean Sheet Glass'
    }
  },

  // --- Category: Corporate & Certificates ---
  {
    id: 'crp-001',
    name: 'Executive A4 Degree & Certificate Frame (Dual Tone Black & Gold)',
    sku: 'JNK-CRT-A4',
    category: 'corporate-framing',
    audience: ['retail', 'wholesale'],
    priceRetail: 380,
    priceWholesale: 195,
    wholesalePackInfo: 'Box of 20 Certificate Frames (₹195/ea - ₹3,900/box)',
    moq: 20,
    rating: 4.8,
    reviewsCount: 240,
    salesCount: 8900,
    isBestseller: true,
    bestsellerType: 'corporate',
    material: 'Composite Polymer',
    finish: 'Matte Black',
    dimensions: 'A4 Size (210 × 297 mm) / 8.3" × 11.7"',
    inStock: true,
    stockCount: 1200,
    photoUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&auto=format&fit=crop&q=80',
    description: 'Bulk favorite for universities, corporate awards ceremonies, doctor clinics, CA offices, and legal advocates. Matte black frame with inner 3mm gold foil border.',
    specs: {
      profileWidth: '22 mm with inner gold accent line',
      orientation: 'Dual portrait or landscape desktop easel + wall hooks',
      glass: 'Polished edge sheet glass',
      packaging: 'Individually shrink-wrapped with corner caps'
    }
  },
  {
    id: 'crp-002',
    name: 'Corporate Boardroom Panorama Wall Art Frame (Satin Black Teak)',
    sku: 'JNK-BRD-2448',
    category: 'corporate-framing',
    audience: ['retail', 'wholesale'],
    priceRetail: 3800,
    priceWholesale: 2100,
    wholesalePackInfo: 'Wholesale: 3+ frames (₹2,100 ea)',
    moq: 3,
    rating: 4.9,
    reviewsCount: 45,
    salesCount: 650,
    isBestseller: false,
    material: 'Solid Wood',
    finish: 'Matte Black',
    dimensions: '24" × 48" Panorama (Ideal for Office Receptions)',
    inStock: true,
    stockCount: 40,
    photoUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&auto=format&fit=crop&q=80',
    description: 'Wide format executive presentation frame for corporate mission statements, skyline photography, architectural blueprints, and boardroom fine art.',
    specs: {
      profileWidth: '35 mm Flat Top Satin Black Timber',
      glazing: 'Shatterproof Lightweight Optical Acrylic',
      hanging: 'Heavy duty Z-cleat french bracket included'
    }
  },
  {
    id: 'crp-003',
    name: 'Employee Recognition & Milestone Award Plaque Frame (Rosewood & Velvet)',
    sku: 'JNK-AWD-1012',
    category: 'corporate-framing',
    audience: ['retail', 'wholesale'],
    priceRetail: 950,
    priceWholesale: 520,
    wholesalePackInfo: 'Min. 10 units for Wholesale (₹520 ea)',
    moq: 10,
    rating: 4.9,
    reviewsCount: 88,
    salesCount: 3100,
    isBestseller: false,
    material: 'Solid Polymer & Brass Inlay',
    finish: 'Warm Teak Wood',
    dimensions: '10" × 12" Tabletop & Wall Plaque',
    inStock: true,
    stockCount: 340,
    photoUrl: 'https://images.unsplash.com/photo-1542744094-3a31f272c490?w=600&auto=format&fit=crop&q=80',
    description: 'Deep luster rosewood profile with velvet backing and brass accent corners. Accommodates metallic printed plates or certificate parchment.',
    specs: {
      profileWidth: '30 mm Chamfered Rosewood Look',
      easelBack: 'Heavy-duty velvet stand for executive desks'
    }
  },

  // --- Category: Retailer Bulk Frame Packs ---
  {
    id: 'blk-001',
    name: 'Retail Store Fast-Seller Photo Frames: 8" × 10" (Master Carton of 24)',
    sku: 'JNK-CS24-810',
    category: 'bulk-retail-cartons',
    audience: ['wholesale'],
    priceRetail: 4800,
    priceWholesale: 2280,
    wholesalePackInfo: 'Master Carton of 24 Frames (₹95.00/unit - Huge Retailer Margin!)',
    moq: 1,
    rating: 4.9,
    reviewsCount: 165,
    salesCount: 7800,
    isBestseller: true,
    bestsellerType: 'bulk-cartons',
    material: 'Composite Polymer',
    finish: 'Assorted (Black, Brown, Gold)',
    dimensions: '8" × 10" (With 5" × 7" Removable Mat)',
    inStock: true,
    stockCount: 180,
    photoUrl: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=600&auto=format&fit=crop&q=80',
    description: 'The #1 fastest selling SKU for gift shops, photo studios, and regional retail outlets. Packed in heavy drop-test certified corrugated boxes with individual bubble sleeves and barcode stickers.',
    specs: {
      packQuantity: '24 Frames in 1 Master Shipping Box',
      glass: 'Washed sheet glass with polished edges',
      easel: 'Two-way velvet kickstand for table + wall hangers',
      profitMargin: 'Over 110% retail markup potential for shopkeepers'
    }
  },
  {
    id: 'blk-002',
    name: 'Temple & Souvenir Shop Bulk Devotional Frames: 6" × 8" (Carton of 40)',
    sku: 'JNK-CS40-68',
    category: 'bulk-retail-cartons',
    audience: ['wholesale'],
    priceRetail: 5200,
    priceWholesale: 2400,
    wholesalePackInfo: 'Carton of 40 Assorted God Frames (₹60.00/unit)',
    moq: 1,
    rating: 4.8,
    reviewsCount: 94,
    salesCount: 9200,
    isBestseller: true,
    bestsellerType: 'bulk-cartons',
    material: 'Gold Finished Polymer',
    finish: 'Temple Antique Gold',
    dimensions: '6" × 8" Table & Wall Pooja Frames',
    inStock: true,
    stockCount: 220,
    photoUrl: 'https://images.unsplash.com/photo-1534349762230-e0cadf78f5da?w=600&auto=format&fit=crop&q=80',
    description: 'High turnover small devotional photo frames for temple gift shops and religious bookstalls. Assortment includes Ram, Hanuman, Krishna, Lakshmi, Shiva and Sai Baba in glittering golden frames.',
    specs: {
      packQuantity: '40 Assorted Deity Frames',
      stand: 'Sturdy fold-out tabletop easel included'
    }
  },
  {
    id: 'blk-003',
    name: 'Modern Square Minimalist Frames: 10" × 10" (Carton of 12)',
    sku: 'JNK-CS12-SQ',
    category: 'bulk-retail-cartons',
    audience: ['wholesale'],
    priceRetail: 3600,
    priceWholesale: 1800,
    wholesalePackInfo: 'Carton of 12 Frames (₹150.00/unit)',
    moq: 1,
    rating: 4.7,
    reviewsCount: 62,
    salesCount: 3400,
    isBestseller: false,
    material: 'Composite Timber',
    finish: 'Crisp White',
    dimensions: '10" × 10" with 5" × 5" Square Opening Mat',
    inStock: true,
    stockCount: 90,
    photoUrl: 'https://images.unsplash.com/photo-1544457070-4cd773b4d71e?w=600&auto=format&fit=crop&q=80',
    description: 'Contemporary Scandinavian white gallery frames for home decor boutiques and modern art galleries. Features bevel cut thick white matboard.',
    specs: {
      packQuantity: '12 Frames in protective master box',
      glazing: 'Clear sheet glass'
    }
  },

  // --- Category: Family & Personal Collages ---
  {
    id: 'fam-001',
    name: 'Newborn Baby Milestone 12-Month First Year Photo Frame',
    sku: 'JNK-BABY-12',
    category: 'family-personal',
    audience: ['retail', 'wholesale'],
    priceRetail: 1650,
    priceWholesale: 880,
    wholesalePackInfo: 'Wholesale: 6+ units (₹880 ea)',
    moq: 6,
    rating: 5.0,
    reviewsCount: 135,
    salesCount: 2900,
    isBestseller: false,
    material: 'Composite Timber',
    finish: 'Crisp White',
    dimensions: '16" × 20" (12 Monthly Cutouts + 1 Large Center)',
    inStock: true,
    stockCount: 115,
    photoUrl: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?w=600&auto=format&fit=crop&q=80',
    description: 'Cherish every month of your baby’s first year from newborn to first birthday. High-precision laser cut beveled mat with soft silver or gold frame trim.',
    specs: {
      openings: '12 circular/oval mini slots + 1 large central 5×7 slot',
      finishTone: 'Soft Pearl White with Gold Inlay'
    }
  },
  {
    id: 'fam-002',
    name: 'Scandinavian Teak Wood 7-Piece Gallery Wall Set',
    sku: 'JNK-GAL-SET7',
    category: 'family-personal',
    audience: ['retail', 'wholesale'],
    priceRetail: 2950,
    priceWholesale: 1650,
    wholesalePackInfo: 'Wholesale: 4+ sets (₹1,650/set)',
    moq: 4,
    rating: 4.9,
    reviewsCount: 98,
    salesCount: 1600,
    isBestseller: false,
    material: 'Solid Wood',
    finish: 'Warm Teak Wood',
    dimensions: 'Set of 7 (1× 12x16, 2× 8x10, 4× 5x7)',
    inStock: true,
    stockCount: 75,
    photoUrl: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=600&auto=format&fit=crop&q=80',
    description: 'Transform your living room wall with a curated 7-piece matching frame set. Includes full-scale hanging template for easy nail alignment.',
    specs: {
      contents: '1 Large, 2 Medium, 4 Small Frames + Wall Hanging Paper Template',
      wood: 'Seasoned natural wood finish'
    }
  },

  // --- Category: Mouldings & Raw Workshop Materials ---
  {
    id: 'mld-001',
    name: 'Synthetic PS Antique Temple Gold Moulding Bars (Bundle 10 × 9.5 ft)',
    sku: 'JNK-MLD-GLD10',
    category: 'mouldings',
    audience: ['wholesale', 'materials'],
    priceRetail: 2400,
    priceWholesale: 1350,
    wholesalePackInfo: 'Wholesale Bundle: 10 Bars / 95 Linear Feet (₹14.20/ft)',
    moq: 1,
    rating: 4.9,
    reviewsCount: 78,
    salesCount: 3800,
    isBestseller: true,
    bestsellerType: 'materials',
    material: 'Synthetic PS Polymer',
    finish: 'Temple Antique Gold',
    dimensions: '9.5 Feet (2.9 Meters) Length Bars',
    inStock: true,
    stockCount: 350,
    photoUrl: 'https://images.unsplash.com/photo-1516455590571-18256e5bb9ff?w=600&auto=format&fit=crop&q=80',
    description: 'The framing industry standard for Hindu god frames, wedding portraits, and ornate art. High-density polystyrene moulding with anti-chip gold foil wrap. Cuts cleanly on mitre saws.',
    specs: {
      profileWidth: '50 mm (2.0 in) Width × 28 mm Depth',
      rebateDepth: '16 mm (0.63 in)',
      bundlePacking: '10 bars tied with corrugated corner protectors'
    }
  },
  {
    id: 'mld-002',
    name: 'Seasoned Teakwood Finish Box Moulding Sticks (Bundle 10 × 9.5 ft)',
    sku: 'JNK-MLD-TEAK',
    category: 'mouldings',
    audience: ['wholesale', 'materials'],
    priceRetail: 2600,
    priceWholesale: 1480,
    wholesalePackInfo: 'Wholesale Bundle: 95 Linear Feet (₹15.50/ft)',
    moq: 1,
    rating: 4.8,
    reviewsCount: 52,
    salesCount: 2400,
    isBestseller: false,
    material: 'Solid Wood',
    finish: 'Warm Teak Wood',
    dimensions: '9.5 Feet Length Sticks (10 per bundle)',
    inStock: true,
    stockCount: 160,
    photoUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
    description: 'Contemporary deep box profile with rich natural teak wood grain texture. Perfect for canvas paintings, deep pooja frames, and corporate art.',
    specs: {
      profileWidth: '25 mm face × 38 mm depth',
      rebateDepth: '30 mm deep rebate'
    }
  },
  {
    id: 'mat-001',
    name: 'Workshop Framing Flexipoint Tabs & Heavy D-Rings (Combo Pack)',
    sku: 'JNK-HDW-COMBO',
    category: 'framing-materials',
    audience: ['wholesale', 'materials'],
    priceRetail: 850,
    priceWholesale: 480,
    wholesalePackInfo: 'Box of 5,000 Flexipoints + 200 Heavy D-Rings (₹480)',
    moq: 1,
    rating: 5.0,
    reviewsCount: 114,
    salesCount: 5100,
    isBestseller: true,
    bestsellerType: 'materials',
    material: 'High-Carbon Steel',
    finish: 'Matte Black',
    dimensions: 'Standard 15mm Flexipoints + 2-Hole D-Rings',
    inStock: true,
    stockCount: 420,
    photoUrl: 'https://images.unsplash.com/photo-1581244277943-fe4a9c777189?w=600&auto=format&fit=crop&q=80',
    description: 'Essential workshop supplies for picture framers and shop craftsmen. High-tensile bendable black flexipoints compatible with manual and pneumatic guns, plus rustproof zinc-coated D-rings.',
    specs: {
      flexipointsCount: '5,000 tabs per box',
      dringsCount: '200 heavy-gauge steel D-rings with screws',
      compatibility: 'Fits Fletcher, Logan and domestic pneumatic framing tools'
    }
  }
];
